version: "3.8"

services:
  sveltekit:
    container_name: ${PROJECT_NAME?err}_sveltekit_dev
    image: ${PROJECT_NAME?err}_sveltekit_dev
    restart: on-failure
    ports:
      - 5173:5173
    build:
      context: ./sveltekit
      dockerfile: Dockerfile.dev
    volumes:
      - ./sveltekit:/usr/src/app
