name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3.5.2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Create env file
        working-directory: ./sveltekit
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          
      - name: Install npm dependencies and build
        working-directory: ./sveltekit
        run: |
          npm install
          npm run build --if-present
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ${{ secrets.REMOTE_TARGET }}
          
      - name: Deploy build
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "sveltekit/"
          EXCLUDE: "${{ secrets.EXCLUDE_FILES }}"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            PATH="$PATH:${{ secrets.PATH }}"
            cd ${{ secrets.REMOTE_TARGET }}
            pm2 delete ${{ secrets.PM2_NAME }} || :
            PORT=${{ secrets.PRODUCTION_PORT }} pm2 start build/index.js --name '${{ secrets.PM2_NAME }}'
            pm2 save
            echo $RSYNC_STDOUT
