name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3.5.2
        
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: sveltekit/${{ secrets.SOURCE }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            SCRIPT_AFTER: |
              ls ${{ secrets.REMOTE_TARGET }}
              PATH="$PATH:${{ secrets.PATH }}"
              which node
              which pm2
              ${{ secrets.PM2_PATH }} delete ${{ secrets.PM2_NAME }} || :
              PORT=${{ secrets.PRODUCTION_PORT }} ${{ secrets.PM2_PATH }} start ${{ secrets.REMOTE_TARGET }}/index.js \
              --name '${{ secrets.PM2_NAME }}'
