name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3.5.2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Create env file
        working-directory: ./sveltekit
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          
      - name: Install npm dependencies and build
        working-directory: ./sveltekit
        run: |
          npm install
          npm run build --if-present
        
      - name: Copy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: sveltekit/${{ secrets.SOURCE }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            
      - name: Remote SSH Commands
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: |
            pm2 delete ${{ secrets.PM2_NAME }} || :
            PORT=${{ secrets.PRODUCTION_PORT }} pm2 start ${{ secrets.secrets.REMOTE_TARGET }}/index.js --name '${{ secrets.PM2_NAME }}'
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # SSH parameters for example: -tt.
          # args: # optional
